### ISSUE TITLE
Include Dr. in english suppressions

### ISSUE THREAD

**Issue by romanakash** [camertron/cldr-segmentation.js#12]
I found a "D." in the en suppression file. But no "Dr." Should be the easiest fix ever

**Comment by camertron** [comment]
Hey @romanakash thanks for the bug report. That seems like a fairly glaring error in the English suppression data, since "Dr." is very common. The suppressions come directly from the CLDR segmentation rules data set, specifically [this XML file](https://github.com/unicode-org/cldr/blob/master/common/segments/en.xml). Unfortunately "Dr." isn't listed. I can add it, but it'll be overwritten the next time I run the code generator. I'll have to come up with a way to add "non-standard" suppressions. Shouldn't be too hard.

**Comment by KevinSoulat** [comment]
Hi @romanakash,

I faced a similar issue with German date (eg. "Heute ist der 28. September." shouldn't break between "28." and "September") and I used [custom suppressions](https://github.com/camertron/cldr-segmentation.js#custom-suppressions) to solve that:

```javascript
const cldr = require("cldr-segmentation");

const rules = {
  de: [
	  {
	    break: false,
	    beforebreak: /\d+\./,
	    afterbreak: /\s(Januar|Jänner|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember)/
	  },
	  {
	    break: false,
	    beforebreak: /\d+\./,
	    afterbreak: /\s(Jan|Jän|Feb|Febr|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Sept|Okt|Nov|Dez)/
	  },
      //...
  ]
}

const shouldBreak = rules => cursor => {

  if( cursor.logicalPosition === cursor.length ){ return true; }

  const before = cursor.text.substring( cursor.logicalPosition-100, cursor.logicalPosition-1 );
  const after = cursor.text.substring( cursor.logicalPosition-1, cursor.logicalPosition+100 );

  const match = ({beforebreak, afterbreak}) => before.match(new RegExp(`${beforebreak.source}$`)) && after.match(new RegExp(`^${afterbreak.source}`));

  const rule = rules.find(match);
  return rule ? rule.break : true;

}

cldr.suppressions.de.shouldBreak = shouldBreak(rules.de);

// ...

const source = 'Heute ist der 28. September.';
const segments = cldr.sentenceSplit(source, cldr.suppressions.de)

```

**Comment by camertron** [comment]
Hey @romanakash and @KevinSoulat, I just published v2.1.0 with support for custom suppressions, eg:

```javascript
var customSupps = cldrSegmentation.Suppressions.create(['Dr.']);
var supps = cldrSegmentation.suppressions.en.merge(customSupps);
cldrSegmentation.sentenceSplit("We love Dr. Strange. He's cool.", supps);
```

Also, by default, English suppressions now contain "Dr." and it should be much easier to add new ones in the future.

**Comment by zenflow** [comment]
@romanakash @camertron "Dr." should have been added to English suppressions in https://github.com/unicode-org/cldr
There shouldn't really be a need for custom suppressions, except as a stop-gap, since that repo accepts PRs

**Comment by camertron** [comment]
@zenflow that's a great point, thanks!
