### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory.

### ISSUE THREAD

**Issue by briunsilo** [camertron/cldr-segmentation.js#14]
I run into the same issues as #13 when trying to use this library in a react application.

Steps to reproduce:

- Create app by running `npx create-react-app cldr-segmentation`
- Add dependency `"cldr-segmentation": "^2.1.0"` to package.json and run `npm install`
- Add `const cldrSegmentation = require('cldr-segmentation');` to App.js
- Run `npm start`

Platform: Mac
Node: v12.14.1
npm: 6.13.4

**Comment by camertron** [comment]
See #13 for details. Should be fixed in v2.1.1. Thanks!

**Comment by briunsilo** [comment]
Thank you so much, it works really great! This is my new favorite library 🥇
