### ISSUE TITLE
per language behaviour for wordSplit

### ISSUE THREAD

**Issue by bittlingmayer** [camertron/cldr-segmentation.js#2]
There are some cases like English `don't` where most parsers split into two words.

For me this is not an issue.

A more difficult case to hardcode are Italian and French contractions, which are very productive because many pronouns and many forms of the indefinite and definite article are contracted when the following word starts with a vowel.

For me and I assume for most clients, it would be ideal to split `l'example` into `l'` and 'example'.  (Same for other chars representing apostrophe, `l’example`.)

The difference here is that `don't` typically is an entry in dictionaries and so on, same for `c'est`, because they are relatively fixed constructions, not the result of productive processes applied to arbitrary words.

**Comment by camertron** [comment]
Hmm that's an interesting use-case... do you think it would require a dictionary or is it enough to simply add a word boundary at apostrophes after single letters?

Unfortunately this library simply uses the existing CLDR segmentation rules, which don't consider contractions (for any language). We could always file a ticket with them, but I don't believe there are any current provisions for locale-specific word break rules in the data set (per-locale ULI exceptions exist for sentence breaking however). There would need to be some mechanism added to this project that would allow the segmentation rules to be customized. Since the rules are really just regular expressions, it should be pretty easy to implement. I don't really have a lot of free time to handle something like that, but would gladly accept a pull request 😄

**Comment by bittlingmayer** [comment]
Thank you for the thorough reply

> do you think it would require a dictionary or is it enough to simply add a word boundary at apostrophes after single letters?

For French and Italian, either way would work, with two caveats:

1. It could be more than a single letter in cases like `un'` or `dell'`.

2. Named entities can be arbitrary, and that includes things like `Sotheby's` and `D'Israeli` (which both occur in both French and English data).

1 may be different for different languages.  Right now in my own code I just made a dictionary, because it is very short even if we are very thorough.

2 is hard to solve fully.  My code only matches lowercase, so I miss those at the start of a sentence.

> Unfortunately this library simply uses the existing CLDR segmentation rules, which don't consider contractions (for any language).

Since this library has "CLDR" in the name, it would probably not be a great idea to implement behaviour that diverges from CLDR, especially by default.

On the other hand, it is odd to have an exception for `U.S.A.` and `S.p.A.` at the sentence level but not at the word level, then we get words like `U.S.A` and `S.p.A`.

So regardless of adding additional exceptions for contractions, it would be good apply the current exceptions to word segmentation too.

And if I understand correctly, there are actually already some basic language-specific rules for Japanese, they are just not explicit because the Japanese scripts are unique to the language.

```
seg.wordSplit('これはテストではなく、スティーブジョブズの声です。')
[ 'こ',
  'れ',
  'は',
  'テスト',
  'で',
  'は',
  'な',
  'く',
  '、',
  'スティーブジョブズ',
  'の',
  '声',
  'で',
  'す',
  '。' ]
```
(Basically when it sees Kanji, it splits, when it sees Katakana it does not, and not sure about Hiragana, this is roughly the limit of my Japanese.)

**Comment by camertron** [comment]
@bittlingmayer Apologies for the delay.

> 1 may be different for different languages. Right now in my own code I just made a dictionary, because it is very short even if we are very thorough.

Yeah, that makes sense. I would be in favor of adding that functionality into cldr-segmentation along with custom break rules. They would need to be supplied by the caller, i.e. we wouldn't include actual dictionaries or custom break rules in the package itself.

> Since this library has "CLDR" in the name, it would probably not be a great idea to implement behaviour that diverges from CLDR, especially by default.

Agreed. I think the key bit here is "by default." I could see opting in to such behavior via a flag, or as I mentioned above, by providing custom rules and/or lists of exceptions.

> On the other hand, it is odd to have an exception for U.S.A. and S.p.A. at the sentence level but not at the word level, then we get words like U.S.A and S.p.A.

We should be able to apply exceptions at the word level (they're called ULI exceptions), which is a good idea. I don't see any reason they should be used only for sentence segmentation.

> And if I understand correctly, there are actually already some basic language-specific rules for Japanese, they are just not explicit because the Japanese scripts are unique to the language. (Basically when it sees Kanji, it splits, when it sees Katakana it does not, and not sure about Hiragana, this is roughly the limit of my Japanese.)

Actually I think it splits on runs of Katakana characters, individual Hiragana characters (for some reason I don't understand), and Kanji. My understanding is that Katakana is most often used to spell words that originated in other languages. For example in Japanese "Microsoft" is spelled "マイクロソフト," or "Maikurosofuto," which is written entirely with Katakana characters. The rules included with CLDR are very rudimentary for Japanese and other non-space separated scripts.

**Comment by camertron** [comment]
@bittlingmayer as I mentioned in the other issue, you might consider using custom suppression logic for this. See the README for details.
