### ISSUE TITLE
exceptions to uliExceptions

### ISSUE THREAD

**Issue by bittlingmayer** [camertron/cldr-segmentation.js#3]
Sometimes a uliException word is actually the end of the sentence.

```
seg.sentenceSplit("I live in the U.S.A.  Where do you live?", seg.uliExceptions.en)
```
Actual:
```
[ 'I live in the U.S.A.  Where do you live?' ]
```

Expected:
```
[ 'I live in the U.S.A.  ',  'Where do you live?' ]
```

Obviously this is hard to solve fully without a parser.

**Comment by camertron** [comment]
Hey @bittlingmayer, as you say this is pretty difficult to solve without a parser or some additional sophisticated break rules. With the v2.0 release however you can create custom suppression logic that might, for example, avoid breaking when the next character is uppercase:

```javascript
class MySuppression {
  shouldBreak(cursor) {
    let cp = cursor.getCodePoint();

    if (cp >= 65 && cp <= 90) {
      return true;
    } else {
      return suppressions.en.shouldBreak(cursor);
    }
  }
}
```

Let me know what you think :)
