### ISSUE TITLE
Support using all ULI exceptions in one call

### ISSUE THREAD

**Issue by bittlingmayer** [camertron/cldr-segmentation.js#4]
Some if not most of the exceptions could occur in other languages:

`Несмотря на разнообразие деятельности Alphabet Inc., основной доход компании приносит сегмент интернет-рекламы.`

There could be some clashes where an abbreviation in one language is a word in another, but my instinct says that it helps more than it hurts.

It would be nice to have something like `seg.uliExceptions.ALL`.

(In theory this is achievable with `Array.prototype.concat(...Object.values(seg.uliExceptions))` but it yields `Invalid regular expression` - `Invalid escape`.  Still trying to understand why.)

Right now this partly solved by including eg Italian `S.p.A.` in the English list, but it is a very small fraction of the possibilities.

**Comment by camertron** [comment]
Hey @bittlingmayer, apologies for not responding to this when you filed it. I just released v2.0 of this library which is not only much, much faster, but also ships with the ability to use all ULI exceptions (now called "suppressions") in a single call:

```javascript
cldrSegmentation.sentenceSplit(str, cldrSegmentation.suppressions.all);
```

You can also mix and match:

```javascript
let supp = cldrSegmentation.Suppressions.create(
  cldrSegmentation.suppressions.en.list + cldrSegmentation.suppressions.de.list
);
```

or create your own:

```javascript
let supp = cldrSegmentation.Suppressions.create(['Mr.', 'Mrs.']);
```

Let me know what you think :)
