### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by KevinSoulat** [camertron/cldr-segmentation.js#8]
Hi,

It seems not possible to install the last version 2.0.0 with npm install (npm ERR! Could not install from "node_modules\cldr-segmentation" as it does not contain a package.json file.):
- npm install cldr-segmentation -> failed
- npm install cldr-segmentation@2 -> failed
- npm install cldr-segmentation@2.0.0 -> failed

This is not the case with the version 1:
- npm install cldr-segmentation@1 -> success

See capture.
![Capture200306_15](https://user-images.githubusercontent.com/6510022/76122037-1abbd400-5fc3-11ea-820b-69de81662f7a.png)

Regards,
Kevin

**Comment by KevinSoulat** [comment]
#9

**Comment by camertron** [comment]
Published as v2.0.1.
